# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from sklearn.cluster import KMeans
img = plt.imread('imageSmall.png')

################# A ######################
newImg = np.reshape(img, (img.shape[0] * img.shape[1], img.shape[2])) 
kmeans = KMeans(n_clusters=16, random_state=10).fit(newImg)
mask = kmeans.labels_
centers = kmeans.cluster_centers_

m, n = newImg.shape

################# B ########################
for i in range(m):
  newImg[i] = centers[int(mask[i])]

img = np.reshape(newImg, (img.shape[0], img.shape[1], img.shape[2]))