# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import folium
import pandas as pd
import numpy as np

m = folium.Map(location=[32.427910, 53.688046], zoom_start = 5)

loc = pd.read_csv('covid.csv',header=0)
loc = loc.values
r, _ = loc.shape

for i in range(r):
  folium.Circle(
    radius=1,
    location=loc[i],
    popup='Covid-19 was detected here',
    color='crimson',
    fill=False,
    ).add_to(m)

m

