# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas
df = pandas.read_csv('data.csv',
                     index_col='id',
                     parse_dates=['confirmed_date'],
                     header=0)
print('------------------------------------------------')
print("The columns of file are : ")
print('')
for i in range(df.columns.values.size):
  print('{}: {}'.format(i+1,df.columns.values[i]))
print('------------------------------------------------')

print('')
print('The size of data is :')
print(df.size)
print('------------------------------------------------')