# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas
df = pandas.read_csv('data.csv',
                     index_col='id',
                     parse_dates=['confirmed_date'],
                     header=0)
data_mean = df['birth_year'].mean()
data_std = df['birth_year'].std()
data_min = df['birth_year'].min()
print('----------------------------------------')
print("The min is: {}".format(data_min))
print("The mean is: {}".format(data_mean))
print("The std is: {}".format(data_std))
print('----------------------------------------')