# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas
df = pandas.read_csv('data.csv',
                     index_col='id',
                     parse_dates=['confirmed_date'],
                     header=0)
years = df['birth_year']
print('----------------------------------------')
len_year = len(years)
count_year = years.count()
if(len_year != count_year):
  print('There is null in the birth year')
  df = pandas.read_csv('data.csv',
                     index_col='id',
                    #  na_values={'birth_year':['-1']},
                     na_values=' -1',
                     parse_dates=['confirmed_date'],
                     header=0)
  years = df['birth_year']
  print('empety datas are replaced by NaN')
print('----------------------------------------')