# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas
import matplotlib.pyplot as plt

df = pandas.read_csv('data.csv',
                     index_col='id',
                     na_values=' -1',
                     parse_dates=['confirmed_date'],
                     header=0)

print('----------------------------------------')
############# LINEAR PLOT ##############
df.plot(x='confirmed_date', y='birth_year')
plt.show()

print('----------------------------------------')
############ SCATTER PLOT ###############
df.plot(x='infected_by', y='birth_year',
        kind = 'scatter')
plt.xlabel = 'confirmed date'
plt.ylabel = 'birth date'
plt.show()

print('----------------------------------------')
############## BOX PLOT ###################
df.plot(y = 'birth_year', kind = 'box')
plt.ylabel = "birth year"
plt.show()

print('----------------------------------------')
############# HISTOGRAM ####################
df.plot(y = 'birth_year', kind = 'hist',
        bins=30)
plt.xlabel = "birth year"
plt.show()

print('----------------------------------------')
############# CUMULATIVE DISTRIBUTION #####
df.plot(y = 'birth_year', kind = 'hist',
        cumulative=True, bins=30)
plt.xlabel = "birth year"
plt.show()


print('----------------------------------------')